export const Data = [
{'id':'1','nombreInvitacion':'Esposos Castro Platero','reserva':2},
{'id':'2','nombreInvitacion':'Guillermo Menjívar','reserva':2},
{'id':'3','nombreInvitacion':'Matilde Menjívar','reserva':'1'},
{'id':'4','nombreInvitacion':'Rodrigo Castro','reserva':'1'},
{'id':'5','nombreInvitacion':'Tránsito Menjívar','reserva':'2'},
{'id':'6','nombreInvitacion':'Flor Menjívar','reserva':'2'},
{'id':'7','nombreInvitacion':'Gladys Arévalo','reserva':'1'},
{'id':'8','nombreInvitacion':'Esposos Sosa Platero','reserva':'4'},
{'id':'9','nombreInvitacion':'Mario Platero','reserva':'1'},
{'id':'10','nombreInvitacion':'Elisa Escobar','reserva':'1'},
{'id':'11','nombreInvitacion':'Mario & Fernando Platero','reserva':'2'},
{'id':'12','nombreInvitacion':'William Pérez','reserva':'2'},
{'id':'13','nombreInvitacion':'Carlos Platero y familia','reserva':'5'},
{'id':'14','nombreInvitacion':'Esposos Siliézar Platero','reserva':'2'},
{'id':'15','nombreInvitacion':'Esposos Castaneda ','reserva':'4'},
{'id':'16','nombreInvitacion':'Esposos Crespin','reserva':'2'},
{'id':'17','nombreInvitacion':'Marcos Castro','reserva':'2'},
{'id':'18','nombreInvitacion':'Lorena Castro','reserva':'1'},
{'id':'19','nombreInvitacion':'Maria del Carmen Arévalo','reserva':'1'},
{'id':'20','nombreInvitacion':'Esposos Carillo Arévalo','reserva':'2'},
{'id':'21','nombreInvitacion':'Esposos Arévalo Rodríguez','reserva':'2'},
{'id':'22','nombreInvitacion':'Esposos Cornejo Arévalo','reserva':'2'},
{'id':'23','nombreInvitacion':'Esposos Camacho Arévalo','reserva':'2'},
{'id':'24','nombreInvitacion':'Gloria Cevallos','reserva':'1'},
{'id':'25','nombreInvitacion':'Esposos Castillo Alemán','reserva':'2'},
{'id':'26','nombreInvitacion':'Esposos González Camacho','reserva':'2'},
{'id':'27','nombreInvitacion':'Guillermo Camacho','reserva':'1'},
{'id':'28','nombreInvitacion':'Margarita Rodríguez','reserva':'1'},
{'id':'29','nombreInvitacion':'Esposos Rivera Galán','reserva':'2'},
{'id':'30','nombreInvitacion':'Alejandro Galán','reserva':'2'},
{'id':'31','nombreInvitacion':'Katherine Domínguez Menjívar ','reserva':'1'},
{'id':'32','nombreInvitacion':'Silvia Renderos','reserva':'1'},
{'id':'33','nombreInvitacion':'Valeria García','reserva':'1'},
{'id':'34','nombreInvitacion':'Claudia Auerbach','reserva':'1'},
{'id':'35','nombreInvitacion':'Guisselle Motto','reserva':'1'},
{'id':'36','nombreInvitacion':'Iveth Aguilar','reserva':'1'},
{'id':'37','nombreInvitacion':'Esposos Menéndez Martínez','reserva':'2'},
{'id':'38','nombreInvitacion':'Esposos Estrada Gutierrez','reserva':'2'},
{'id':'39','nombreInvitacion':'Jessica Prieto','reserva':'1'},
{'id':'40','nombreInvitacion':'Priscilla Herrera','reserva':'1'},
{'id':'41','nombreInvitacion':'Karla Anduray','reserva':'1'},
{'id':'42','nombreInvitacion':'Lucila Carías','reserva':'1'},
{'id':'43','nombreInvitacion':'Kenia Monge','reserva':'1'},
{'id':'44','nombreInvitacion':'William Hernandez','reserva':'1'},
{'id':'45','nombreInvitacion':'Esposos Villalobos Granados','reserva':'2'},
{'id':'46','nombreInvitacion':'Lili Melhado','reserva':'2'},
{'id':'47','nombreInvitacion':'Sandra de Díaz','reserva':'1'},
{'id':'48','nombreInvitacion':'Ernesto Pleitez','reserva':'2'},
{'id':'49','nombreInvitacion':'Esposos Morales','reserva':'2'},
{'id':'50','nombreInvitacion':'Sulay Mejía','reserva':'1'},
{'id':'51','nombreInvitacion':'Kevin Álvarez','reserva':'1'},
{'id':'52','nombreInvitacion':'Adrian Miranda','reserva':'1'},
{'id':'53','nombreInvitacion':'Esposos Barahona Hernández','reserva':'2'},
{'id':'54','nombreInvitacion':'Esposos Merino Villalta','reserva':'2'},
{'id':'55','nombreInvitacion':'Esposos Aragón Vásquez','reserva':'2'},
{'id':'56','nombreInvitacion':'Kevin Sasso','reserva':'2'},
{'id':'57','nombreInvitacion':'Giovanni Orellana','reserva':'1'},
{'id':'58','nombreInvitacion':'Esposos Brito Quintanilla','reserva':'2'},
{'id':'59','nombreInvitacion':'Ismael Echeverria','reserva':'1'},
{'id':'60','nombreInvitacion':'Karina Cornejo','reserva':'1'},
{'id':'61','nombreInvitacion':'Christian Bonilla','reserva':'1'},
{'id':'62','nombreInvitacion':'Bryan Carranza','reserva':'1'},
{'id':'63','nombreInvitacion':'Roosevelt Cornejo','reserva':'1'},
{'id':'64','nombreInvitacion':'Vicky Martinez','reserva':'3'},
{'id':'65','nombreInvitacion':'Esposos Menjívar','reserva':'2'},
{'id':'66','nombreInvitacion':'Esposos Estrada','reserva':'2'},
{'id':'67','nombreInvitacion':'Esposos Sánchez Rodriguez','reserva':'2'},
{'id':'68','nombreInvitacion':'Esposos Avilés Castillo','reserva':'2'}
]



